### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by ageev** [opendxl/opendxl-epo-client-python#3]
hi!

Python 3 is not supported, right? Maybe you can add this to repository front page)?
Is there any plans to add Python3 support in the future?

Regards, Artyom

**Comment by jbarlow-mcafee** [comment]
Support for Python 3 was added in the recent [0.2.0 release](https://github.com/opendxl/opendxl-epo-client-python/releases/tag/0.2.0). If you encounter any issues using this new release, please file a new issue. Closing this issue out...
